updated sl homepage url
aureooms-ulb/algo-website pull request #5
Opened 2017-05-17 09:35 UTC by slef

2017-05-17 13:48 UTC, make-github-pseudonymous-again requested changes
https

2017-05-17 13:50 UTC, aureooms commented
You also need to change the image links on your page for them to display. Everything under algo.ulb.be should be https.

2017-05-17 20:19 UTC, slef commented
fixed.

2017-05-20 14:51 UTC, make-github-pseudonymous-again approved these changes

2017-05-20 14:52 UTC, merged